export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const FETCH_EMPLOYEE = 'FETCH_EMPLOYEE';
export const NEW_EMPLOYEE = 'NEW_EMPLOYEE';
export const SAVE_EMPLOYEE = 'SAVE_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';


export const FETCH_EMPLOYEES_PENDING = 'FETCH_EMPLOYEES_PENDING';
export const FETCH_EMPLOYEES_FULFILLED = 'FETCH_EMPLOYEES_FULFILLED';
export const FETCH_EMPLOYEES_REJECTED = 'FETCH_EMPLOYEES_REJECTED';
export const SAVE_EMPLOYEE_PENDING = 'SAVE_EMPLOYEE_PENDING';
export const SAVE_EMPLOYEE_FULFILLED = 'SAVE_EMPLOYEE_FULFILLED';
export const SAVE_EMPLOYEE_REJECTED = 'SAVE_EMPLOYEE_REJECTED';
export const FETCH_EMPLOYEE_PENDING = 'FETCH_EMPLOYEE_PENDING';
export const FETCH_EMPLOYEE_FULFILLED = 'FETCH_EMPLOYEE_FULFILLED';
export const UPDATE_EMPLOYEE_PENDING = 'UPDATE_EMPLOYEE_PENDING';
export const UPDATE_EMPLOYEE_FULFILLED = 'UPDATE_EMPLOYEE_FULFILLED';
export const UPDATE_EMPLOYEE_REJECTED = 'UPDATE_EMPLOYEE_REJECTED';
export const DELETE_EMPLOYEE_FULFILLED = 'DELETE_EMPLOYEE_FULFILLED';